# Generated by Django 4.1.1 on 2022-12-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
