# Generated by Django 4.1.1 on 2022-12-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
